name: Test Scheduler

on:
  schedule:
    # هر ۵ دقیقه اجرا می‌شود
    - cron: '*/5 * * * *'
  workflow_dispatch: # برای اجرای دستی

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello! The scheduler is working correctly at $(date)"
